In [62]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [63]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [64]:
print(x)

[['Indonesia' 44.0 62000.0]
 ['Brazil' 40.0 94000.0]
 ['China' 22.0 73000.0]
 ['Indonesia' 21.0 81000.0]
 ['China' 12.0 nan]
 ['Brazil' 35.0 28000.0]
 ['Brazil' nan 52000.0]
 ['Indonesia' 32.0 79000.0]
 ['China' 14.0 99000.0]
 ['Indonesia' 26.0 73000.0]]


In [68]:
print(y)

['Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak']


In [69]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [70]:
print(x)

[['Indonesia' 44.0 62000.0]
 ['Brazil' 40.0 94000.0]
 ['China' 22.0 73000.0]
 ['Indonesia' 21.0 81000.0]
 ['China' 12.0 71222.22222222222]
 ['Brazil' 35.0 28000.0]
 ['Brazil' 27.333333333333332 52000.0]
 ['Indonesia' 32.0 79000.0]
 ['China' 14.0 99000.0]
 ['Indonesia' 26.0 73000.0]]


In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [72]:
print(x)

[[0.0 0.0 1.0 44.0 62000.0]
 [1.0 0.0 0.0 40.0 94000.0]
 [0.0 1.0 0.0 22.0 73000.0]
 [0.0 0.0 1.0 21.0 81000.0]
 [0.0 1.0 0.0 12.0 71222.22222222222]
 [1.0 0.0 0.0 35.0 28000.0]
 [1.0 0.0 0.0 27.333333333333332 52000.0]
 [0.0 0.0 1.0 32.0 79000.0]
 [0.0 1.0 0.0 14.0 99000.0]
 [0.0 0.0 1.0 26.0 73000.0]]


In [73]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [74]:
print(y)

[1 1 1 0 1 0 0 1 0 0]


In [75]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [76]:
print(x_train)

[[1.0 0.0 0.0 27.333333333333332 52000.0]
 [0.0 1.0 0.0 12.0 71222.22222222222]
 [0.0 0.0 1.0 44.0 62000.0]
 [0.0 0.0 1.0 21.0 81000.0]
 [1.0 0.0 0.0 40.0 94000.0]
 [0.0 0.0 1.0 32.0 79000.0]
 [0.0 1.0 0.0 14.0 99000.0]
 [1.0 0.0 0.0 35.0 28000.0]]


In [77]:
print(x_test)

[[0.0 1.0 0.0 22.0 73000.0]
 [0.0 0.0 1.0 26.0 73000.0]]


In [82]:
print(y_train)

[0 1 1 0 1 1 0 0]


In [78]:
print(y_test)

[1 0]


In [79]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [80]:
print(x_train)

[[1.0 0.0 0.0 -0.07582723791092233 -0.8652740192466486]
 [0.0 1.0 0.0 -1.471048415471895 0.02047985844370736]
 [0.0 0.0 1.0 1.4407175203075266 -0.40447720426322636]
 [0.0 0.0 1.0 -0.6521142460339328 0.4710367442052759]
 [1.0 0.0 0.0 1.0767467783350988 1.070072603683725]
 [0.0 0.0 1.0 0.34880529439024344 0.3788773812085915]
 [0.0 1.0 0.0 -1.2890630444856812 1.300471011175436]
 [1.0 0.0 0.0 0.6217833508695643 -1.971186375206862]]


In [81]:
print(x_test)

[[0.0 1.0 0.0 -0.5611215605408258 0.10239929221853813]
 [0.0 0.0 1.0 -0.1971508185683981 0.10239929221853813]]
